apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "foxmq-metrics.serviceAccountName" . }}
  labels:
    {{- include "foxmq-metrics.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "foxmq-metrics.serviceAccountName" . }}
    apiGroup: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "foxmq-metrics.serviceAccountName" . }}
