apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foxmq-metrics.fullname" . }}
type: Opaque
stringData:
  username: "{{ include "foxmq-metrics.influxDB.username" . }}"
  password: "{{ default (randAlphaNum 16) .Values.influxDB.password }}"
  authToken: "{{ randAlphaNum 32 }}"
