apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: foxmq-demo
spec:
  domains:
    - node-0.demo.foxmq.infra.tashi.dev
    - node-1.demo.foxmq.infra.tashi.dev
    - node-2.demo.foxmq.infra.tashi.dev
    - node-3.demo.foxmq.infra.tashi.dev
