{{- if .Values.bytehound.enable -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foxmq.fullname" . }}
type: Opaque
stringData:
  username: "{{ include "foxmq.bytehound.login.username" . }}"
  password: "{{ default (randAlphaNum 16) .Values.influxDB.password }}"
  authToken: "{{ randAlphaNum 32 }}"
  {{- end -}}
