apiVersion: v1
kind: Service
metadata:
  name: {{ include "foxmq.fullname" . }}-mqtt
  labels:
    {{- include "foxmq.labels" . | nindent 4 }}
spec:
  type: {{ default "NodePort" .Values.service.type }}
  ports:
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: influxdb
      {{ if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  selector:
    {{- include "foxmq.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "foxmq.fullname" . }}-cluster
  labels:
    {{- include "foxmq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 19793
      targetPort: cluster
      protocol: UDP
      name: cluster
  selector:
    {{- include "foxmq.selectorLabels" . | nindent 4 }}
